Fix a bad merge (#766)
One side of the merge removed the final usage of `regexp` from
`insights.go` and so removed `import "regexp"`.  The other side of the
merge introduced an additional usage of `regexp`, so depends on
`import "regexp"`.  The two changes didn't conflict textually, but they
resulted in a branch that does this:

```
  # vitess.io/vitess/go/vt/vtgate
  go/vt/vtgate/insights.go:332:21: undefined: regexp
```

https: //planetscale.slack.com/archives/CM6PGFUJY/p1655141617022779?thread_ts=1655109713.429959&cid=CM6PGFUJY
Signed-off-by: Patrick Reynolds <patrick@piki.org>